name: CI/CD pipeline

on:
  push:
    branches:
      - main
      - staging  # Runs pipeline for staging branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci  # Faster and more reliable than `npm install`

      - name: Set ESLint Permissions
        run: chmod +x node_modules/.bin/eslint  # Fixes permission issue

      - name: Lint Code
        run: npx --no-install eslint .  # Runs locally installed ESLint

      - name: Run tests
        run: npm test  # Ensure tests pass

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'  # Only deploy on staging branch push

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}   # AWS EC2 Public IP (Set in GitHub Secrets)
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}  # Private SSH Key (Set in GitHub Secrets)
          script: |
            git clone https://github.com/SANKEERTHBD/AWS.git
