name: CI/CD pipeline

on:
  push:
    branches:
      - main
      - staging  # Runs pipeline for staging branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Lint Code
        run: npx eslint . || exit 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'  # Only deploy if the push is to 'staging' branch

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}   # Use GitHub Secret
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}  # Use GitHub Secret
          script: |
            cd /var/www/staging
            git pull origin staging
            npm install
            pm2 restart all  # Restart app with PM2
