name: CI/CD pipeline

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Lint Code
        run: npx eslint . ||  exit 1
